<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="31" total="50" passed="19">
  <reporter-output>
    <line>
      <![CDATA[在：2018-01-18 12:39:36:440点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:39:40:807控件：com.thetiger.ziwork:id/phone_e不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:39:44:276点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:39:50:380输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:39:57:352点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:01:826控件：com.thetiger.ziwork:id/edit_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:07:933控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:12:439控件：com.thetiger.ziwork:id/submit_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:46:372通过坐标点击]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:50:571控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:40:54:850控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:06:461重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:09:987点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:14:279控件：com.thetiger.ziwork:id/phone_e不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:18:205点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:23:534输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:30:176点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:34:693控件：com.thetiger.ziwork:id/edit_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:40:189控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:44:349控件：com.thetiger.ziwork:id/submit_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:41:54:728点击了按钮：//android.widget.ImageButton[@content-desc='转到上一层级']]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:01:613控件：com.thetiger.ziwork:id/home_middle_banner不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:06:617通过坐标点击]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:10:630控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:14:768控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:18:912控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:23:089控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:27:224控件：com.thetiger.ziwork:id/main_tab_mine不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:31:389控件：com.thetiger.ziwork:id/zike_info_container不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:35:627控件：com.thetiger.ziwork:id/belong_city_siv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:39:726控件：com.thetiger.ziwork:id/confirm不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:43:844控件：com.thetiger.ziwork:id/work_time_siv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:47:992控件：com.thetiger.ziwork:id/confirm不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:53:008控件：//android.widget.TextView[@text='设计']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:42:57:206控件：com.thetiger.ziwork:id/click_to_select_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:02:083控件：//android.widget.TextView[@text='UI']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:06:128控件：com.thetiger.ziwork:id/confirm_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:10:218控件：com.thetiger.ziwork:id/menu_common不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:14:346控件：com.thetiger.ziwork:id/content_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:18:466控件：com.thetiger.ziwork:id/menu_common不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:22:530控件：com.thetiger.ziwork:id/next_browse_action_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:32:642重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:36:515点击了按钮：com.thetiger.ziwork:id/phone_login_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:41:899输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:46:402点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:50:428控件：com.thetiger.ziwork:id/input_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:43:54:477控件：com.thetiger.ziwork:id/login_phone_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:44:04:308重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:44:22:195点击了按钮：com.thetiger.ziwork:id/wx_login_tv]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="307520" started-at="2018-01-18T04:39:20Z" finished-at="2018-01-18T04:44:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="307520" started-at="2018-01-18T04:39:20Z" finished-at="2018-01-18T04:44:28Z">
      <class name="com.Case.NewTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="beforeSuite" is-config="true" duration-ms="3835" started-at="2018-01-18T12:39:16Z" finished-at="2018-01-18T12:39:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="BeforeClass" is-config="true" duration-ms="10121" started-at="2018-01-18T12:39:20Z" finished-at="2018-01-18T12:39:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="1688" started-at="2018-01-18T12:39:34Z" data-provider="testing" finished-at="2018-01-18T12:39:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册(领新人礼包)]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即进入]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/novice_gift_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:39:36:440点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4381" started-at="2018-01-18T12:39:36Z" data-provider="testing" finished-at="2018-01-18T12:39:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_e]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[随机]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:39:40:807控件：com.thetiger.ziwork:id/phone_e不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:39:36Z" finished-at="2018-01-18T12:39:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="3453" started-at="2018-01-18T12:39:40Z" data-provider="testing" finished-at="2018-01-18T12:39:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:39:44:276点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:39:40Z" finished-at="2018-01-18T12:39:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:39:44Z" finished-at="2018-01-18T12:39:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="6102" started-at="2018-01-18T12:39:44Z" data-provider="testing" finished-at="2018-01-18T12:39:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:39:50:380输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:39:50Z" finished-at="2018-01-18T12:39:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="6971" started-at="2018-01-18T12:39:50Z" data-provider="testing" finished-at="2018-01-18T12:39:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/title_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:39:57:352点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:39:57Z" finished-at="2018-01-18T12:39:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4470" started-at="2018-01-18T12:39:57Z" data-provider="testing" finished-at="2018-01-18T12:40:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入姓名]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/edit_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[自客123456]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:01:826控件：com.thetiger.ziwork:id/edit_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:01Z" finished-at="2018-01-18T12:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="6107" started-at="2018-01-18T12:40:01Z" data-provider="testing" finished-at="2018-01-18T12:40:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入职位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.EditText[@text='如：文案达人']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[开发测试工程师]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:07:933控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:07Z" finished-at="2018-01-18T12:40:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4503" started-at="2018-01-18T12:40:07Z" data-provider="testing" finished-at="2018-01-18T12:40:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/submit_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:12:439控件：com.thetiger.ziwork:id/submit_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:12Z" finished-at="2018-01-18T12:40:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="33933" started-at="2018-01-18T12:40:12Z" data-provider="testing" finished-at="2018-01-18T12:40:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击一键领取]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Strongclick]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:46:372通过坐标点击]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4198" started-at="2018-01-18T12:40:46Z" data-provider="testing" finished-at="2018-01-18T12:40:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击已购领取的小课]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:50:571控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:46Z" finished-at="2018-01-18T12:40:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:50Z" finished-at="2018-01-18T12:40:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4280" started-at="2018-01-18T12:40:50Z" data-provider="testing" finished-at="2018-01-18T12:40:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即播放]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/pause_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:40:54:850控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="13609" started-at="2018-01-18T12:40:54Z" data-provider="testing" finished-at="2018-01-18T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:06:461重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:40:54Z" finished-at="2018-01-18T12:40:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:41:08Z" finished-at="2018-01-18T12:41:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="1524" started-at="2018-01-18T12:41:08Z" data-provider="testing" finished-at="2018-01-18T12:41:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[13]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册(首页领新人福利)]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即进入]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/novice_gift_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:09:987点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4290" started-at="2018-01-18T12:41:09Z" data-provider="testing" finished-at="2018-01-18T12:41:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[14]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_e]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[随机]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:14:279控件：com.thetiger.ziwork:id/phone_e不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:09Z" finished-at="2018-01-18T12:41:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="3925" started-at="2018-01-18T12:41:14Z" data-provider="testing" finished-at="2018-01-18T12:41:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:18:205点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:14Z" finished-at="2018-01-18T12:41:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:41:18Z" finished-at="2018-01-18T12:41:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="5327" started-at="2018-01-18T12:41:18Z" data-provider="testing" finished-at="2018-01-18T12:41:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:23:534输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:41:23Z" finished-at="2018-01-18T12:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="6639" started-at="2018-01-18T12:41:23Z" data-provider="testing" finished-at="2018-01-18T12:41:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[17]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/title_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:30:176点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:30Z" finished-at="2018-01-18T12:41:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4500" started-at="2018-01-18T12:41:30Z" data-provider="testing" finished-at="2018-01-18T12:41:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入姓名]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/edit_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[自客123456]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:34:693控件：com.thetiger.ziwork:id/edit_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:34Z" finished-at="2018-01-18T12:41:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="5493" started-at="2018-01-18T12:41:34Z" data-provider="testing" finished-at="2018-01-18T12:41:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[19]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入职位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.EditText[@text='如：文案达人']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[开发测试工程师]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:40:189控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:40Z" finished-at="2018-01-18T12:41:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4156" started-at="2018-01-18T12:41:40Z" data-provider="testing" finished-at="2018-01-18T12:41:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/submit_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:44:349控件：com.thetiger.ziwork:id/submit_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="10380" started-at="2018-01-18T12:41:44Z" data-provider="testing" finished-at="2018-01-18T12:41:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[21]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击返回，出现大弹窗]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.ImageButton[@content-desc='转到上一层级']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/home_banner_sdv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:41:54:728点击了按钮：//android.widget.ImageButton[@content-desc='转到上一层级']]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:44Z" finished-at="2018-01-18T12:41:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="2596" started-at="2018-01-18T12:41:54Z" data-provider="testing" finished-at="2018-01-18T12:41:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[22]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[出现弹窗，点掉]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/close_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[ispopup]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:41:54Z" finished-at="2018-01-18T12:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:41:57Z" finished-at="2018-01-18T12:41:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4284" started-at="2018-01-18T12:41:57Z" data-provider="testing" finished-at="2018-01-18T12:42:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[23]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击首页新人大礼包占位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/home_middle_banner]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:01:613控件：com.thetiger.ziwork:id/home_middle_banner不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:01Z" finished-at="2018-01-18T12:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="5002" started-at="2018-01-18T12:42:01Z" data-provider="testing" finished-at="2018-01-18T12:42:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[24]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击一键领取]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Strongclick]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:06:617通过坐标点击]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="2" started-at="2018-01-18T12:42:06Z" finished-at="2018-01-18T12:42:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4008" started-at="2018-01-18T12:42:06Z" data-provider="testing" finished-at="2018-01-18T12:42:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击已购领取的小课]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:10:630控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:10Z" finished-at="2018-01-18T12:42:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4138" started-at="2018-01-18T12:42:10Z" data-provider="testing" finished-at="2018-01-18T12:42:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即播放]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/pause_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:14:768控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4142" started-at="2018-01-18T12:42:14Z" data-provider="testing" finished-at="2018-01-18T12:42:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[27]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册完之后认证自客（认证两步流程）]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[返回到详情]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/course_back_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/bottom_play_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:18:912控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:14Z" finished-at="2018-01-18T12:42:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:18Z" finished-at="2018-01-18T12:42:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4176" started-at="2018-01-18T12:42:18Z" data-provider="testing" finished-at="2018-01-18T12:42:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[28]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[返回到首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/course_back_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:23:089控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:23Z" finished-at="2018-01-18T12:42:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4133" started-at="2018-01-18T12:42:23Z" data-provider="testing" finished-at="2018-01-18T12:42:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[29]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击我的]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_mine]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/collection_siv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:27:224控件：com.thetiger.ziwork:id/main_tab_mine不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:27Z" finished-at="2018-01-18T12:42:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4161" started-at="2018-01-18T12:42:27Z" data-provider="testing" finished-at="2018-01-18T12:42:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完善信息]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/zike_info_container]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:31:389控件：com.thetiger.ziwork:id/zike_info_container不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4239" started-at="2018-01-18T12:42:31Z" data-provider="testing" finished-at="2018-01-18T12:42:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[31]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击所在城市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/belong_city_siv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:35:627控件：com.thetiger.ziwork:id/belong_city_siv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:31Z" finished-at="2018-01-18T12:42:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:35Z" finished-at="2018-01-18T12:42:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4094" started-at="2018-01-18T12:42:35Z" data-provider="testing" finished-at="2018-01-18T12:42:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[32]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:39:726控件：com.thetiger.ziwork:id/confirm不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:39Z" finished-at="2018-01-18T12:42:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4115" started-at="2018-01-18T12:42:39Z" data-provider="testing" finished-at="2018-01-18T12:42:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[33]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击工作年限]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/work_time_siv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:43:844控件：com.thetiger.ziwork:id/work_time_siv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:43Z" finished-at="2018-01-18T12:42:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4144" started-at="2018-01-18T12:42:43Z" data-provider="testing" finished-at="2018-01-18T12:42:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:47:992控件：com.thetiger.ziwork:id/confirm不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:47Z" finished-at="2018-01-18T12:42:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="5013" started-at="2018-01-18T12:42:47Z" data-provider="testing" finished-at="2018-01-18T12:42:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[35]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击选择一个技能类别]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.TextView[@text='设计']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:53:008控件：//android.widget.TextView[@text='设计']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:42:53Z" finished-at="2018-01-18T12:42:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4194" started-at="2018-01-18T12:42:53Z" data-provider="testing" finished-at="2018-01-18T12:42:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击技能标签]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/click_to_select_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:42:57:206控件：com.thetiger.ziwork:id/click_to_select_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:42:57Z" finished-at="2018-01-18T12:42:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4877" started-at="2018-01-18T12:42:57Z" data-provider="testing" finished-at="2018-01-18T12:43:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[37]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击选择UI]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.TextView[@text='UI']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:02:083控件：//android.widget.TextView[@text='UI']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:43:02Z" finished-at="2018-01-18T12:43:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4043" started-at="2018-01-18T12:43:02Z" data-provider="testing" finished-at="2018-01-18T12:43:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[38]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:06:128控件：com.thetiger.ziwork:id/confirm_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="2" started-at="2018-01-18T12:43:06Z" finished-at="2018-01-18T12:43:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4085" started-at="2018-01-18T12:43:06Z" data-provider="testing" finished-at="2018-01-18T12:43:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[39]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击下一步]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:10:218控件：com.thetiger.ziwork:id/menu_common不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:10Z" finished-at="2018-01-18T12:43:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4126" started-at="2018-01-18T12:43:10Z" data-provider="testing" finished-at="2018-01-18T12:43:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[40]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入自我介绍]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/content_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[我是一个非常非常优秀的游戏达人]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:14:346控件：com.thetiger.ziwork:id/content_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:14Z" finished-at="2018-01-18T12:43:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4116" started-at="2018-01-18T12:43:14Z" data-provider="testing" finished-at="2018-01-18T12:43:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[41]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成，到成功页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/next_browse_action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:18:466控件：com.thetiger.ziwork:id/menu_common不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="2" started-at="2018-01-18T12:43:18Z" finished-at="2018-01-18T12:43:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4059" started-at="2018-01-18T12:43:18Z" data-provider="testing" finished-at="2018-01-18T12:43:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击去首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/next_browse_action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:22:530控件：com.thetiger.ziwork:id/next_browse_action_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:22Z" finished-at="2018-01-18T12:43:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="12108" started-at="2018-01-18T12:43:22Z" data-provider="testing" finished-at="2018-01-18T12:43:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[43]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:32:642重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:43:34Z" finished-at="2018-01-18T12:43:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="1866" started-at="2018-01-18T12:43:34Z" data-provider="testing" finished-at="2018-01-18T12:43:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[44]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[登录]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击手机号登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_login_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:36:515点击了按钮：com.thetiger.ziwork:id/phone_login_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:43:36Z" finished-at="2018-01-18T12:43:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="5383" started-at="2018-01-18T12:43:36Z" data-provider="testing" finished-at="2018-01-18T12:43:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[13700000000]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:41:899输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:41Z" finished-at="2018-01-18T12:43:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4501" started-at="2018-01-18T12:43:41Z" data-provider="testing" finished-at="2018-01-18T12:43:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[46]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:46:402点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:46Z" finished-at="2018-01-18T12:43:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4023" started-at="2018-01-18T12:43:46Z" data-provider="testing" finished-at="2018-01-18T12:43:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[47]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:50:428控件：com.thetiger.ziwork:id/input_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:43:50Z" finished-at="2018-01-18T12:43:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="4046" started-at="2018-01-18T12:43:50Z" data-provider="testing" finished-at="2018-01-18T12:43:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[48]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录，跳转首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:43:54:477控件：com.thetiger.ziwork:id/login_phone_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="11827" started-at="2018-01-18T12:43:54Z" data-provider="testing" finished-at="2018-01-18T12:44:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[49]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:44:04:308重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:43:54Z" finished-at="2018-01-18T12:43:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="5" started-at="2018-01-18T12:44:06Z" finished-at="2018-01-18T12:44:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@5a8e6209]" name="testcase" duration-ms="15881" started-at="2018-01-18T12:44:06Z" data-provider="testing" finished-at="2018-01-18T12:44:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[微信登录]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击微信登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/wx_login_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:44:22:195点击了按钮：com.thetiger.ziwork:id/wx_login_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:44:22Z" finished-at="2018-01-18T12:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="afterClass" is-config="true" duration-ms="6153" started-at="2018-01-18T12:44:22Z" finished-at="2018-01-18T12:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.Case.NewTest@5a8e6209]" name="afterSuite" is-config="true" duration-ms="205" started-at="2018-01-18T12:44:28Z" finished-at="2018-01-18T12:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.Case.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
